"""Fetch public Steam libraries for candidate player IDs.

This pipeline stage:
1. Reads the selected SteamIDs from data/interim/steamids_unique.csv.
2. Calls Steam Web API GetOwnedGames for each player.
3. Stores one row per returned player-game relationship.
4. Classifies each candidate profile by accessibility and data usability.
5. Exports summary metrics used to estimate the final collection size.

This stage does not classify games into combat, exploration or puzzle.
"""

from __future__ import annotations

import argparse
import csv
import json
import logging
import os
import sys
import time
from collections import Counter
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import requests
from dotenv import load_dotenv
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry


PROJECT_ROOT = Path(__file__).resolve().parents[1]

DEFAULT_INPUT = PROJECT_ROOT / "data" / "interim" / "steamids_unique.csv"
DEFAULT_GAMES_OUTPUT = PROJECT_ROOT / "data" / "raw" / "player_games_raw.csv"
DEFAULT_STATUS_OUTPUT = PROJECT_ROOT / "data" / "interim" / "player_library_status.csv"
DEFAULT_SUMMARY_OUTPUT = (
    PROJECT_ROOT / "reports" / "metrics" / "02_player_games_summary.json"
)

GET_OWNED_GAMES_ENDPOINT = (
    "https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/"
)

LOGGER = logging.getLogger("player-games-collector")

INPUT_REQUIRED_FIELDS = {"steamid"}

GAME_FIELDNAMES = [
    "player_id",
    "appid",
    "playtime_forever_minutes",
    "playtime_2weeks_minutes",
    "rtime_last_played",
    "last_played_at",
    "playtime_windows_forever_minutes",
    "playtime_mac_forever_minutes",
    "playtime_linux_forever_minutes",
    "playtime_deck_forever_minutes",
    "collected_at",
]

STATUS_FIELDNAMES = [
    "player_id",
    "source_steamid",
    "status",
    "game_count_reported",
    "games_returned",
    "games_with_positive_playtime",
    "total_playtime_minutes",
    "http_status",
    "attempts",
    "error",
    "collected_at",
]


@dataclass(frozen=True)
class CandidatePlayer:
    """Candidate selected in the previous pipeline stage."""

    player_id: str
    steamid: str


@dataclass
class FetchResult:
    """Normalized result of one GetOwnedGames request."""

    status: str
    games: list[dict[str, Any]]
    game_count_reported: int
    http_status: int | None
    attempts: int
    error: str | None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fetch public Steam libraries for candidate SteamIDs."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help="CSV generated by 01_collect_steamids.py.",
    )
    parser.add_argument(
        "--games-output",
        type=Path,
        default=DEFAULT_GAMES_OUTPUT,
        help="Output CSV with one row per player-game relationship.",
    )
    parser.add_argument(
        "--status-output",
        type=Path,
        default=DEFAULT_STATUS_OUTPUT,
        help="Output CSV with one accessibility status per player.",
    )
    parser.add_argument(
        "--summary-output",
        type=Path,
        default=DEFAULT_SUMMARY_OUTPUT,
        help="Output JSON with collection and viability metrics.",
    )
    parser.add_argument(
        "--request-delay",
        type=float,
        default=1.0,
        help="Delay in seconds between player requests. Default: 1.0.",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=30.0,
        help="HTTP timeout in seconds. Default: 30.",
    )
    parser.add_argument(
        "--max-players",
        type=int,
        default=None,
        help="Optional limit for a smaller test run.",
    )
    parser.add_argument(
        "--target-valid",
        type=int,
        default=1000,
        help="Desired number of usable public profiles for estimation.",
    )
    parser.add_argument(
        "--minimum-games",
        type=int,
        default=1,
        help="Minimum number of returned games required for provisional validity.",
    )
    parser.add_argument(
        "--minimum-played-games",
        type=int,
        default=1,
        help=(
            "Minimum number of games with positive playtime required for "
            "provisional validity."
        ),
    )

    args = parser.parse_args()

    if args.request_delay < 0:
        parser.error("--request-delay cannot be negative.")
    if args.timeout <= 0:
        parser.error("--timeout must be greater than zero.")
    if args.max_players is not None and args.max_players <= 0:
        parser.error("--max-players must be greater than zero.")
    if args.target_valid <= 0:
        parser.error("--target-valid must be greater than zero.")
    if args.minimum_games <= 0:
        parser.error("--minimum-games must be greater than zero.")
    if args.minimum_played_games <= 0:
        parser.error("--minimum-played-games must be greater than zero.")

    return args


def configure_logging() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
    )


def load_api_key() -> str:
    load_dotenv(PROJECT_ROOT / ".env")
    api_key = os.getenv("STEAM_API_KEY", "").strip()

    if not api_key:
        raise ValueError(
            "STEAM_API_KEY was not found. Create ai-model/.env using "
            ".env.example and add your Steam Web API key."
        )

    return api_key


def load_candidates(
    input_path: Path,
    max_players: int | None,
) -> list[CandidatePlayer]:
    if not input_path.exists():
        raise FileNotFoundError(f"Input file not found: {input_path}")

    candidates: list[CandidatePlayer] = []
    steamids_seen: set[str] = set()

    with input_path.open("r", encoding="utf-8", newline="") as file:
        reader = csv.DictReader(file)

        if reader.fieldnames is None:
            raise ValueError(f"Input CSV has no header: {input_path}")

        missing_fields = INPUT_REQUIRED_FIELDS - set(reader.fieldnames)
        if missing_fields:
            raise ValueError(
                f"Input CSV is missing fields: {sorted(missing_fields)}"
            )

        for index, row in enumerate(reader, start=1):
            steamid = str(row.get("steamid", "")).strip()

            if not steamid.isdigit():
                LOGGER.warning(
                    "Ignoring invalid SteamID at CSV row %d: %r",
                    index + 1,
                    steamid,
                )
                continue

            if steamid in steamids_seen:
                LOGGER.warning(
                    "Ignoring duplicated SteamID at CSV row %d: %s",
                    index + 1,
                    steamid,
                )
                continue

            steamids_seen.add(steamid)
            candidates.append(
                CandidatePlayer(
                    player_id=f"player_{len(candidates) + 1:04d}",
                    steamid=steamid,
                )
            )

            if max_players is not None and len(candidates) >= max_players:
                break

    if not candidates:
        raise ValueError("No valid SteamIDs were found in the input CSV.")

    return candidates


def create_http_session() -> requests.Session:
    retry_strategy = Retry(
        total=5,
        connect=5,
        read=5,
        status=5,
        backoff_factor=1.0,
        status_forcelist=(429, 500, 502, 503, 504),
        allowed_methods=frozenset({"GET"}),
        raise_on_status=False,
    )

    adapter = HTTPAdapter(max_retries=retry_strategy)
    session = requests.Session()
    session.mount("https://", adapter)
    session.headers.update(
        {
            "User-Agent": (
                "AdaptiveTrials-AcademicResearch/1.0 "
                "(public Steam library collector)"
            )
        }
    )
    return session


def safe_int(value: Any) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return 0


def unix_timestamp_to_iso(value: Any) -> str:
    timestamp = safe_int(value)
    if timestamp <= 0:
        return ""

    return datetime.fromtimestamp(timestamp, tz=timezone.utc).isoformat()


def fetch_owned_games(
    session: requests.Session,
    api_key: str,
    steamid: str,
    timeout: float,
) -> FetchResult:
    """Fetch a player's visible library.

    Steam commonly returns an empty response object when game details are not
    publicly visible. This response cannot reliably distinguish a private
    library from another unavailable profile state, so the script records
    `private_or_unavailable` rather than guessing a more specific reason.
    """

    try:
        response = session.get(
            GET_OWNED_GAMES_ENDPOINT,
            params={
                "key": api_key,
                "steamid": steamid,
                "include_appinfo": "false",
                "include_played_free_games": "true",
                "format": "json",
            },
            timeout=timeout,
        )
    except requests.RequestException as error:
        return FetchResult(
            status="request_error",
            games=[],
            game_count_reported=0,
            http_status=None,
            attempts=1,
            error=str(error),
        )

    if response.status_code in {401, 403}:
        raise PermissionError(
            "Steam rejected the API key. Verify STEAM_API_KEY in ai-model/.env."
        )

    if response.status_code != requests.codes.ok:
        return FetchResult(
            status="request_error",
            games=[],
            game_count_reported=0,
            http_status=response.status_code,
            attempts=1,
            error=f"HTTP {response.status_code}",
        )

    try:
        payload = response.json()
    except requests.JSONDecodeError as error:
        return FetchResult(
            status="invalid_response",
            games=[],
            game_count_reported=0,
            http_status=response.status_code,
            attempts=1,
            error=f"Invalid JSON: {error}",
        )

    response_payload = payload.get("response")

    if not isinstance(response_payload, dict) or not response_payload:
        return FetchResult(
            status="private_or_unavailable",
            games=[],
            game_count_reported=0,
            http_status=response.status_code,
            attempts=1,
            error=None,
        )

    game_count = safe_int(response_payload.get("game_count"))
    raw_games = response_payload.get("games")

    if game_count == 0 and not raw_games:
        return FetchResult(
            status="empty_library",
            games=[],
            game_count_reported=0,
            http_status=response.status_code,
            attempts=1,
            error=None,
        )

    if not isinstance(raw_games, list):
        return FetchResult(
            status="invalid_response",
            games=[],
            game_count_reported=game_count,
            http_status=response.status_code,
            attempts=1,
            error="Response contained no valid games list.",
        )

    games = [game for game in raw_games if isinstance(game, dict)]

    return FetchResult(
        status="accessible",
        games=games,
        game_count_reported=game_count,
        http_status=response.status_code,
        attempts=1,
        error=None,
    )


def normalize_game_row(
    player_id: str,
    game: dict[str, Any],
    collected_at: str,
) -> dict[str, Any] | None:
    appid = safe_int(game.get("appid"))
    if appid <= 0:
        return None

    return {
        "player_id": player_id,
        "appid": appid,
        "playtime_forever_minutes": safe_int(
            game.get("playtime_forever")
        ),
        "playtime_2weeks_minutes": safe_int(
            game.get("playtime_2weeks")
        ),
        "rtime_last_played": safe_int(game.get("rtime_last_played")),
        "last_played_at": unix_timestamp_to_iso(
            game.get("rtime_last_played")
        ),
        "playtime_windows_forever_minutes": safe_int(
            game.get("playtime_windows_forever")
        ),
        "playtime_mac_forever_minutes": safe_int(
            game.get("playtime_mac_forever")
        ),
        "playtime_linux_forever_minutes": safe_int(
            game.get("playtime_linux_forever")
        ),
        "playtime_deck_forever_minutes": safe_int(
            game.get("playtime_deck_forever")
        ),
        "collected_at": collected_at,
    }


def determine_final_status(
    fetch_status: str,
    games_returned: int,
    games_with_positive_playtime: int,
    minimum_games: int,
    minimum_played_games: int,
) -> str:
    if fetch_status != "accessible":
        return fetch_status

    if games_returned < minimum_games:
        return "insufficient_games"

    if games_with_positive_playtime < minimum_played_games:
        return "no_playtime"

    return "valid"


def collect_player_games(
    candidates: list[CandidatePlayer],
    session: requests.Session,
    api_key: str,
    request_delay: float,
    timeout: float,
    minimum_games: int,
    minimum_played_games: int,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    all_game_rows: list[dict[str, Any]] = []
    status_rows: list[dict[str, Any]] = []

    collected_at = datetime.now(timezone.utc).isoformat()
    total = len(candidates)

    for index, candidate in enumerate(candidates, start=1):
        result = fetch_owned_games(
            session=session,
            api_key=api_key,
            steamid=candidate.steamid,
            timeout=timeout,
        )

        normalized_games: list[dict[str, Any]] = []

        for game in result.games:
            normalized = normalize_game_row(
                player_id=candidate.player_id,
                game=game,
                collected_at=collected_at,
            )
            if normalized is not None:
                normalized_games.append(normalized)

        games_with_positive_playtime = sum(
            1
            for game in normalized_games
            if safe_int(game["playtime_forever_minutes"]) > 0
        )
        total_playtime_minutes = sum(
            safe_int(game["playtime_forever_minutes"])
            for game in normalized_games
        )

        final_status = determine_final_status(
            fetch_status=result.status,
            games_returned=len(normalized_games),
            games_with_positive_playtime=games_with_positive_playtime,
            minimum_games=minimum_games,
            minimum_played_games=minimum_played_games,
        )

        # Only accessible libraries produce player-game rows. Profiles may be
        # classified as no_playtime or insufficient_games while their returned
        # games remain preserved for audit.
        all_game_rows.extend(normalized_games)

        status_rows.append(
            {
                "player_id": candidate.player_id,
                "source_steamid": candidate.steamid,
                "status": final_status,
                "game_count_reported": result.game_count_reported,
                "games_returned": len(normalized_games),
                "games_with_positive_playtime": games_with_positive_playtime,
                "total_playtime_minutes": total_playtime_minutes,
                "http_status": (
                    result.http_status
                    if result.http_status is not None
                    else ""
                ),
                "attempts": result.attempts,
                "error": result.error or "",
                "collected_at": collected_at,
            }
        )

        LOGGER.info(
            "[%d/%d] %s: status=%s, games=%d, played=%d.",
            index,
            total,
            candidate.player_id,
            final_status,
            len(normalized_games),
            games_with_positive_playtime,
        )

        if request_delay > 0 and index < total:
            time.sleep(request_delay)

    return all_game_rows, status_rows


def write_csv(
    output_path: Path,
    rows: list[dict[str, Any]],
    fieldnames: list[str],
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = output_path.with_suffix(output_path.suffix + ".tmp")

    with temporary_path.open("w", encoding="utf-8", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    temporary_path.replace(output_path)


def write_json(output_path: Path, payload: dict[str, Any]) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = output_path.with_suffix(output_path.suffix + ".tmp")

    with temporary_path.open("w", encoding="utf-8") as file:
        json.dump(payload, file, ensure_ascii=False, indent=2)

    temporary_path.replace(output_path)


def build_summary(
    candidates: list[CandidatePlayer],
    game_rows: list[dict[str, Any]],
    status_rows: list[dict[str, Any]],
    args: argparse.Namespace,
    started_at: datetime,
    finished_at: datetime,
) -> dict[str, Any]:
    status_counts = Counter(str(row["status"]) for row in status_rows)
    valid_profiles = status_counts.get("valid", 0)
    attempted_profiles = len(status_rows)
    accessible_profiles = sum(
        count
        for status, count in status_counts.items()
        if status in {"valid", "no_playtime", "insufficient_games"}
    )

    access_rate = (
        accessible_profiles / attempted_profiles
        if attempted_profiles
        else 0.0
    )
    valid_yield_rate = (
        valid_profiles / attempted_profiles
        if attempted_profiles
        else 0.0
    )

    estimated_candidates = (
        args.target_valid / valid_yield_rate
        if valid_yield_rate > 0
        else None
    )
    estimated_candidates_rounded_up = (
        int(estimated_candidates)
        if estimated_candidates is not None
        and estimated_candidates.is_integer()
        else (
            int(estimated_candidates) + 1
            if estimated_candidates is not None
            else None
        )
    )

    valid_player_ids = {
        str(row["player_id"])
        for row in status_rows
        if row["status"] == "valid"
    }
    valid_game_rows = [
        row for row in game_rows if str(row["player_id"]) in valid_player_ids
    ]

    valid_total_playtime = sum(
        safe_int(row["playtime_forever_minutes"])
        for row in valid_game_rows
    )

    return {
        "pipeline_stage": "02_fetch_player_games",
        "started_at": started_at.isoformat(),
        "finished_at": finished_at.isoformat(),
        "duration_seconds": round(
            (finished_at - started_at).total_seconds(),
            3,
        ),
        "parameters": {
            "request_delay": args.request_delay,
            "timeout": args.timeout,
            "max_players": args.max_players,
            "target_valid": args.target_valid,
            "minimum_games": args.minimum_games,
            "minimum_played_games": args.minimum_played_games,
            "include_played_free_games": True,
            "include_appinfo": False,
        },
        "candidate_profiles_loaded": len(candidates),
        "profiles_attempted": attempted_profiles,
        "status_counts": dict(sorted(status_counts.items())),
        "accessible_profiles": accessible_profiles,
        "valid_profiles": valid_profiles,
        "access_rate": round(access_rate, 6),
        "valid_yield_rate": round(valid_yield_rate, 6),
        "estimated_candidates_for_target": estimated_candidates_rounded_up,
        "target_valid_profiles": args.target_valid,
        "player_game_rows": len(game_rows),
        "valid_player_game_rows": len(valid_game_rows),
        "unique_appids_returned": len(
            {safe_int(row["appid"]) for row in game_rows}
        ),
        "valid_unique_appids": len(
            {safe_int(row["appid"]) for row in valid_game_rows}
        ),
        "valid_total_playtime_minutes": valid_total_playtime,
        "valid_total_playtime_hours": round(
            valid_total_playtime / 60,
            3,
        ),
        "methodological_note": (
            "The valid status is provisional. Final usability also depends on "
            "the proportion of library games that can be categorized after "
            "game metadata collection and category mapping."
        ),
    }


def main() -> int:
    configure_logging()
    args = parse_args()
    started_at = datetime.now(timezone.utc)

    try:
        api_key = load_api_key()
        candidates = load_candidates(args.input, args.max_players)
        session = create_http_session()

        game_rows, status_rows = collect_player_games(
            candidates=candidates,
            session=session,
            api_key=api_key,
            request_delay=args.request_delay,
            timeout=args.timeout,
            minimum_games=args.minimum_games,
            minimum_played_games=args.minimum_played_games,
        )

        write_csv(
            output_path=args.games_output,
            rows=game_rows,
            fieldnames=GAME_FIELDNAMES,
        )
        write_csv(
            output_path=args.status_output,
            rows=status_rows,
            fieldnames=STATUS_FIELDNAMES,
        )

        finished_at = datetime.now(timezone.utc)
        summary = build_summary(
            candidates=candidates,
            game_rows=game_rows,
            status_rows=status_rows,
            args=args,
            started_at=started_at,
            finished_at=finished_at,
        )
        write_json(args.summary_output, summary)

    except PermissionError as error:
        LOGGER.error("%s", error)
        return 3
    except (OSError, ValueError, requests.RequestException) as error:
        LOGGER.exception("Player library collection failed: %s", error)
        return 1

    LOGGER.info(
        "Collection completed: profiles=%d, game rows=%d.",
        len(status_rows),
        len(game_rows),
    )
    LOGGER.info("Games output: %s", args.games_output)
    LOGGER.info("Status output: %s", args.status_output)
    LOGGER.info("Summary output: %s", args.summary_output)

    return 0


if __name__ == "__main__":
    sys.exit(main())