// <auto-generated />
using System;
using AdaptiveTrials.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdaptiveTrials.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924195000_AlignMissionParametersWithGameplay")]
    partial class AlignMissionParametersWithGameplay
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.BehaviorEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CompletionTime")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Failures")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissionType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Persistence")
                        .HasColumnType("REAL");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("SessionId");

                    b.ToTable("BehaviorEvents");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Missions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Derrotar o alvo protegido por poucos inimigos.",
                            Difficulty = 1,
                            Name = "Caça Simples",
                            ParametersJson = "{\"targetHealth\":5,\"guards\":1}",
                            Template = "Eliminar Alvo",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Derrotar um alvo mais resistente protegido por uma quantidade intermediária de inimigos.",
                            Difficulty = 2,
                            Name = "Caça Média",
                            ParametersJson = "{\"targetHealth\":7,\"guards\":2}",
                            Template = "Eliminar Alvo",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Derrotar um alvo de alta resistência protegido por vários inimigos.",
                            Difficulty = 3,
                            Name = "Caça Elite",
                            ParametersJson = "{\"targetHealth\":10,\"guards\":3}",
                            Template = "Eliminar Alvo",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sobreviver e eliminar três ondas de inimigos.",
                            Difficulty = 1,
                            Name = "Sobrevivência Inicial",
                            ParametersJson = "{\"waves\":3}",
                            Template = "Sobreviver",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sobreviver e eliminar cinco ondas de dificuldade progressiva.",
                            Difficulty = 2,
                            Name = "Sobrevivência Intermediária",
                            ParametersJson = "{\"waves\":5}",
                            Template = "Sobreviver",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Sobreviver e eliminar sete ondas de inimigos sob alta pressão.",
                            Difficulty = 3,
                            Name = "Sobrevivência Extrema",
                            ParametersJson = "{\"waves\":7}",
                            Template = "Sobreviver",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Defender o cristal durante poucas ondas, adaptando-se aos reposicionamentos após dano.",
                            Difficulty = 1,
                            Name = "Defesa Básica",
                            ParametersJson = "{\"waves\":2,\"objectHealth\":14}",
                            Template = "Defender Objeto",
                            Type = 1
                        },
                        new
                        {
                            Id = 23,
                            Description = "Defender o cristal durante uma quantidade intermediária de ondas, adaptando-se aos reposicionamentos após dano.",
                            Difficulty = 2,
                            Name = "Defesa Intermediária",
                            ParametersJson = "{\"waves\":3,\"objectHealth\":12}",
                            Template = "Defender Objeto",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Defender o cristal contra várias ondas, adaptando-se aos reposicionamentos após dano.",
                            Difficulty = 3,
                            Name = "Defesa Avançada",
                            ParametersJson = "{\"waves\":5,\"objectHealth\":10}",
                            Template = "Defender Objeto",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Explorar um labirinto simples com visibilidade limitada para encontrar poucos objetos.",
                            Difficulty = 1,
                            Name = "Exploração Simples",
                            ParametersJson = "{\"items\":3,\"lightScale\":3.0}",
                            Template = "Encontrar Objetos",
                            Type = 2
                        },
                        new
                        {
                            Id = 10,
                            Description = "Explorar um labirinto intermediário com visibilidade reduzida para encontrar objetos distribuídos pelo cenário.",
                            Difficulty = 2,
                            Name = "Exploração Média",
                            ParametersJson = "{\"items\":6,\"lightScale\":2.35}",
                            Template = "Encontrar Objetos",
                            Type = 2
                        },
                        new
                        {
                            Id = 11,
                            Description = "Explorar um labirinto complexo com baixa visibilidade para encontrar todos os objetos.",
                            Difficulty = 3,
                            Name = "Exploração Difícil",
                            ParametersJson = "{\"items\":10,\"lightScale\":1.75}",
                            Template = "Encontrar Objetos",
                            Type = 2
                        },
                        new
                        {
                            Id = 12,
                            Description = "Percorrer uma rota curta seguindo checkpoints e atravessando poucos obstáculos temporizados.",
                            Difficulty = 1,
                            Name = "Navegação Simples",
                            ParametersJson = "{\"checkpoints\":2,\"hazards\":2,\"lasers\":1,\"maxFailures\":4,\"safeSeconds\":2.8,\"warningSeconds\":1.15,\"activeSeconds\":1.0}",
                            Template = "Chegar ao Destino",
                            Type = 2
                        },
                        new
                        {
                            Id = 24,
                            Description = "Percorrer uma rota intermediária seguindo checkpoints e sincronizando a travessia de obstáculos temporizados.",
                            Difficulty = 2,
                            Name = "Navegação Intermediária",
                            ParametersJson = "{\"checkpoints\":3,\"hazards\":4,\"lasers\":3,\"maxFailures\":3,\"safeSeconds\":2.0,\"warningSeconds\":0.8,\"activeSeconds\":1.25}",
                            Template = "Chegar ao Destino",
                            Type = 2
                        },
                        new
                        {
                            Id = 13,
                            Description = "Percorrer uma rota complexa com vários checkpoints, lasers e áreas energizadas de janelas reduzidas.",
                            Difficulty = 3,
                            Name = "Navegação Complexa",
                            ParametersJson = "{\"checkpoints\":5,\"hazards\":6,\"lasers\":5,\"maxFailures\":2,\"safeSeconds\":1.35,\"warningSeconds\":0.55,\"activeSeconds\":1.55}",
                            Template = "Chegar ao Destino",
                            Type = 2
                        },
                        new
                        {
                            Id = 14,
                            Description = "Atravessar uma rota de furtividade com poucas patrulhas, usando cobertura e pontos seguros.",
                            Difficulty = 1,
                            Name = "Furtividade Básica",
                            ParametersJson = "{\"enemies\":2,\"enemySpeed\":65,\"detectionRadius\":70,\"coneAngle\":52,\"suspicionSeconds\":1.35,\"safePoints\":1,\"maxFailures\":4}",
                            Template = "Evitar Inimigos",
                            Type = 2
                        },
                        new
                        {
                            Id = 25,
                            Description = "Atravessar uma rota de furtividade intermediária com múltiplas patrulhas, cobertura e pontos seguros.",
                            Difficulty = 2,
                            Name = "Furtividade Intermediária",
                            ParametersJson = "{\"enemies\":4,\"enemySpeed\":85,\"detectionRadius\":90,\"coneAngle\":68,\"suspicionSeconds\":0.9,\"safePoints\":2,\"maxFailures\":3}",
                            Template = "Evitar Inimigos",
                            Type = 2
                        },
                        new
                        {
                            Id = 15,
                            Description = "Atravessar uma rota de furtividade avançada com várias patrulhas, cones de visão amplos e menor tempo de reação.",
                            Difficulty = 3,
                            Name = "Furtividade Avançada",
                            ParametersJson = "{\"enemies\":6,\"enemySpeed\":110,\"detectionRadius\":115,\"coneAngle\":88,\"suspicionSeconds\":0.55,\"safePoints\":3,\"maxFailures\":2}",
                            Template = "Evitar Inimigos",
                            Type = 2
                        },
                        new
                        {
                            Id = 16,
                            Description = "Repetir uma sequência curta de símbolos.",
                            Difficulty = 1,
                            Name = "Sequência Simples",
                            ParametersJson = "{\"sequenceSize\":3,\"maxFailures\":4}",
                            Template = "Repetir Sequência",
                            Type = 3
                        },
                        new
                        {
                            Id = 17,
                            Description = "Repetir uma sequência de tamanho intermediário.",
                            Difficulty = 2,
                            Name = "Sequência Média",
                            ParametersJson = "{\"sequenceSize\":5,\"maxFailures\":3}",
                            Template = "Repetir Sequência",
                            Type = 3
                        },
                        new
                        {
                            Id = 18,
                            Description = "Repetir uma sequência longa de alta exigência de memória.",
                            Difficulty = 3,
                            Name = "Sequência Difícil",
                            ParametersJson = "{\"sequenceSize\":8,\"maxFailures\":2}",
                            Template = "Repetir Sequência",
                            Type = 3
                        },
                        new
                        {
                            Id = 19,
                            Description = "Conectar poucos pares de pontos respeitando as regras do tabuleiro.",
                            Difficulty = 1,
                            Name = "Conexão Básica",
                            ParametersJson = "{\"pieces\":4,\"maxFailures\":5}",
                            Template = "Conectar Pontos",
                            Type = 3
                        },
                        new
                        {
                            Id = 26,
                            Description = "Conectar uma quantidade intermediária de pares de pontos respeitando as regras do tabuleiro.",
                            Difficulty = 2,
                            Name = "Conexão Intermediária",
                            ParametersJson = "{\"pieces\":6,\"maxFailures\":4}",
                            Template = "Conectar Pontos",
                            Type = 3
                        },
                        new
                        {
                            Id = 20,
                            Description = "Conectar vários pares de pontos em um tabuleiro de maior complexidade.",
                            Difficulty = 3,
                            Name = "Conexão Avançada",
                            ParametersJson = "{\"pieces\":8,\"maxFailures\":3}",
                            Template = "Conectar Pontos",
                            Type = 3
                        },
                        new
                        {
                            Id = 21,
                            Description = "Descobrir uma sequência oculta de cinco símbolos em até seis tentativas.",
                            Difficulty = 1,
                            Name = "Código Simples",
                            ParametersJson = "{\"boards\":1,\"attempts\":6}",
                            Template = "Decifrar Código",
                            Type = 3
                        },
                        new
                        {
                            Id = 27,
                            Description = "Descobrir duas sequências ocultas simultaneamente em até sete tentativas.",
                            Difficulty = 2,
                            Name = "Código Intermediário",
                            ParametersJson = "{\"boards\":2,\"attempts\":7}",
                            Template = "Decifrar Código",
                            Type = 3
                        },
                        new
                        {
                            Id = 22,
                            Description = "Descobrir quatro sequências ocultas simultaneamente em até nove tentativas.",
                            Difficulty = 3,
                            Name = "Código Difícil",
                            ParametersJson = "{\"boards\":4,\"attempts\":9}",
                            Template = "Decifrar Código",
                            Type = 3
                        });
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.NormalizedProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AvgPlaytimePerGame")
                        .HasColumnType("REAL");

                    b.Property<double>("Combat")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Diversity")
                        .HasColumnType("REAL");

                    b.Property<double?>("Dominance")
                        .HasColumnType("REAL");

                    b.Property<double?>("Entropy")
                        .HasColumnType("REAL");

                    b.Property<double>("Exploration")
                        .HasColumnType("REAL");

                    b.Property<int>("GamesCombat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesExploration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesPuzzle")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Gap")
                        .HasColumnType("REAL");

                    b.Property<double>("HoursCombat")
                        .HasColumnType("REAL");

                    b.Property<double>("HoursExploration")
                        .HasColumnType("REAL");

                    b.Property<double>("HoursPuzzle")
                        .HasColumnType("REAL");

                    b.Property<int>("NumGames")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Puzzle")
                        .HasColumnType("REAL");

                    b.Property<double?>("SecondMax")
                        .HasColumnType("REAL");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalPlaytime")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("NormalizedProfiles");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManualPreferencesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SteamId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BehaviorWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("CombatProbability")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ExplorationProbability")
                        .HasColumnType("REAL");

                    b.Property<int?>("MissionId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ProfileWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("PuzzleProbability")
                        .HasColumnType("REAL");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecommendedDifficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecommendedType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("SessionId");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.BehaviorEvent", b =>
                {
                    b.HasOne("AdaptiveTrials.Domain.Entities.Mission", "Mission")
                        .WithMany("BehaviorEvents")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdaptiveTrials.Domain.Entities.GameSession", "Session")
                        .WithMany("BehaviorEvents")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.GameSession", b =>
                {
                    b.HasOne("AdaptiveTrials.Domain.Entities.Player", "Player")
                        .WithMany("Sessions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.NormalizedProfile", b =>
                {
                    b.HasOne("AdaptiveTrials.Domain.Entities.Player", "Player")
                        .WithOne("NormalizedProfile")
                        .HasForeignKey("AdaptiveTrials.Domain.Entities.NormalizedProfile", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.Recommendation", b =>
                {
                    b.HasOne("AdaptiveTrials.Domain.Entities.Mission", "Mission")
                        .WithMany("Recommendations")
                        .HasForeignKey("MissionId");

                    b.HasOne("AdaptiveTrials.Domain.Entities.GameSession", "Session")
                        .WithMany("Recommendations")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.GameSession", b =>
                {
                    b.Navigation("BehaviorEvents");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.Mission", b =>
                {
                    b.Navigation("BehaviorEvents");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.Player", b =>
                {
                    b.Navigation("NormalizedProfile");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
