// <auto-generated />
using System;
using AdaptiveTrials.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdaptiveTrials.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723225922_NormalizeMissionDifficulties")]
    partial class NormalizeMissionDifficulties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.BehaviorEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CompletionTime")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Failures")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissionType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Persistence")
                        .HasColumnType("REAL");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("SessionId");

                    b.ToTable("BehaviorEvents");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Missions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Derrotar uma pequena quantidade de inimigos.",
                            Difficulty = 1,
                            Name = "Caça Simples",
                            ParametersJson = "{\"enemies\":3,\"boss\":false}",
                            Template = "Eliminar Alvo",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Derrotar uma quantidade intermediária de inimigos.",
                            Difficulty = 2,
                            Name = "Caça Média",
                            ParametersJson = "{\"enemies\":6,\"boss\":false}",
                            Template = "Eliminar Alvo",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Derrotar um inimigo de elite.",
                            Difficulty = 3,
                            Name = "Caça Elite",
                            ParametersJson = "{\"enemies\":1,\"boss\":true}",
                            Template = "Eliminar Alvo",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Resistir por um curto período de tempo.",
                            Difficulty = 1,
                            Name = "Sobrevivência Curta",
                            ParametersJson = "{\"timeSeconds\":30}",
                            Template = "Sobreviver",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Resistir por um período intermediário.",
                            Difficulty = 2,
                            Name = "Sobrevivência Média",
                            ParametersJson = "{\"timeSeconds\":60}",
                            Template = "Sobreviver",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Resistir por um período prolongado sob alta pressão.",
                            Difficulty = 3,
                            Name = "Sobrevivência Extrema",
                            ParametersJson = "{\"timeSeconds\":120}",
                            Template = "Sobreviver",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Defender um objeto durante poucas ondas.",
                            Difficulty = 1,
                            Name = "Defesa Básica",
                            ParametersJson = "{\"waves\":2}",
                            Template = "Defender Objeto",
                            Type = 1
                        },
                        new
                        {
                            Id = 23,
                            Description = "Defender um objeto durante uma quantidade intermediária de ondas.",
                            Difficulty = 2,
                            Name = "Defesa Intermediária",
                            ParametersJson = "{\"waves\":3}",
                            Template = "Defender Objeto",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Defender um objeto contra várias ondas.",
                            Difficulty = 3,
                            Name = "Defesa Avançada",
                            ParametersJson = "{\"waves\":5}",
                            Template = "Defender Objeto",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Buscar poucos itens pelo cenário.",
                            Difficulty = 1,
                            Name = "Exploração Simples",
                            ParametersJson = "{\"items\":3}",
                            Template = "Encontrar Objetos",
                            Type = 2
                        },
                        new
                        {
                            Id = 10,
                            Description = "Buscar uma quantidade intermediária de itens.",
                            Difficulty = 2,
                            Name = "Exploração Média",
                            ParametersJson = "{\"items\":6}",
                            Template = "Encontrar Objetos",
                            Type = 2
                        },
                        new
                        {
                            Id = 11,
                            Description = "Buscar muitos itens em uma missão de alta complexidade.",
                            Difficulty = 3,
                            Name = "Exploração Difícil",
                            ParametersJson = "{\"items\":10}",
                            Template = "Encontrar Objetos",
                            Type = 2
                        },
                        new
                        {
                            Id = 12,
                            Description = "Chegar ao destino por uma rota curta e pouco perigosa.",
                            Difficulty = 1,
                            Name = "Navegação Simples",
                            ParametersJson = "{\"distance\":\"short\",\"checkpoints\":2,\"hazards\":2,\"maxFailures\":4}",
                            Template = "Chegar ao Destino",
                            Type = 2
                        },
                        new
                        {
                            Id = 24,
                            Description = "Chegar ao destino por uma rota de complexidade intermediária.",
                            Difficulty = 2,
                            Name = "Navegação Intermediária",
                            ParametersJson = "{\"distance\":\"medium\",\"checkpoints\":3,\"hazards\":4,\"maxFailures\":3}",
                            Template = "Chegar ao Destino",
                            Type = 2
                        },
                        new
                        {
                            Id = 13,
                            Description = "Chegar ao destino por uma rota longa e perigosa.",
                            Difficulty = 3,
                            Name = "Navegação Complexa",
                            ParametersJson = "{\"distance\":\"long\",\"checkpoints\":5,\"hazards\":6,\"maxFailures\":2}",
                            Template = "Chegar ao Destino",
                            Type = 2
                        },
                        new
                        {
                            Id = 14,
                            Description = "Evitar poucos inimigos durante o percurso.",
                            Difficulty = 1,
                            Name = "Stealth Básico",
                            ParametersJson = "{\"enemies\":2,\"enemySpeed\":65,\"detectionRadius\":70,\"maxFailures\":4}",
                            Template = "Evitar Inimigos",
                            Type = 2
                        },
                        new
                        {
                            Id = 25,
                            Description = "Evitar patrulhas de velocidade e alcance intermediários.",
                            Difficulty = 2,
                            Name = "Stealth Intermediário",
                            ParametersJson = "{\"enemies\":4,\"enemySpeed\":85,\"detectionRadius\":90,\"maxFailures\":3}",
                            Template = "Evitar Inimigos",
                            Type = 2
                        },
                        new
                        {
                            Id = 15,
                            Description = "Evitar várias patrulhas em uma missão de alta dificuldade.",
                            Difficulty = 3,
                            Name = "Stealth Avançado",
                            ParametersJson = "{\"enemies\":6,\"enemySpeed\":110,\"detectionRadius\":115,\"maxFailures\":2}",
                            Template = "Evitar Inimigos",
                            Type = 2
                        },
                        new
                        {
                            Id = 16,
                            Description = "Repetir uma sequência curta.",
                            Difficulty = 1,
                            Name = "Sequência Simples",
                            ParametersJson = "{\"sequenceSize\":3}",
                            Template = "Repetir Sequência",
                            Type = 3
                        },
                        new
                        {
                            Id = 17,
                            Description = "Repetir uma sequência de tamanho intermediário.",
                            Difficulty = 2,
                            Name = "Sequência Média",
                            ParametersJson = "{\"sequenceSize\":5}",
                            Template = "Repetir Sequência",
                            Type = 3
                        },
                        new
                        {
                            Id = 18,
                            Description = "Repetir uma sequência de alta exigência de memória.",
                            Difficulty = 3,
                            Name = "Sequência Difícil",
                            ParametersJson = "{\"sequenceSize\":8}",
                            Template = "Repetir Sequência",
                            Type = 3
                        },
                        new
                        {
                            Id = 19,
                            Description = "Resolver uma conexão simples entre pontos.",
                            Difficulty = 1,
                            Name = "Conexão Básica",
                            ParametersJson = "{\"pieces\":4}",
                            Template = "Conectar Pontos",
                            Type = 3
                        },
                        new
                        {
                            Id = 26,
                            Description = "Resolver uma conexão de complexidade intermediária.",
                            Difficulty = 2,
                            Name = "Conexão Intermediária",
                            ParametersJson = "{\"pieces\":6}",
                            Template = "Conectar Pontos",
                            Type = 3
                        },
                        new
                        {
                            Id = 20,
                            Description = "Resolver uma conexão complexa entre vários pontos.",
                            Difficulty = 3,
                            Name = "Conexão Avançada",
                            ParametersJson = "{\"pieces\":8}",
                            Template = "Conectar Pontos",
                            Type = 3
                        },
                        new
                        {
                            Id = 21,
                            Description = "Decifrar um código com várias pistas disponíveis.",
                            Difficulty = 1,
                            Name = "Código Simples",
                            ParametersJson = "{\"clues\":3}",
                            Template = "Decifrar Código",
                            Type = 3
                        },
                        new
                        {
                            Id = 27,
                            Description = "Decifrar um código com uma quantidade intermediária de pistas.",
                            Difficulty = 2,
                            Name = "Código Intermediário",
                            ParametersJson = "{\"clues\":2}",
                            Template = "Decifrar Código",
                            Type = 3
                        },
                        new
                        {
                            Id = 22,
                            Description = "Decifrar um código com poucas pistas disponíveis.",
                            Difficulty = 3,
                            Name = "Código Difícil",
                            ParametersJson = "{\"clues\":1}",
                            Template = "Decifrar Código",
                            Type = 3
                        });
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.NormalizedProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AvgPlaytimePerGame")
                        .HasColumnType("REAL");

                    b.Property<double>("Combat")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Diversity")
                        .HasColumnType("REAL");

                    b.Property<double?>("Dominance")
                        .HasColumnType("REAL");

                    b.Property<double?>("Entropy")
                        .HasColumnType("REAL");

                    b.Property<double>("Exploration")
                        .HasColumnType("REAL");

                    b.Property<int>("GamesCombat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesExploration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesPuzzle")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Gap")
                        .HasColumnType("REAL");

                    b.Property<double>("HoursCombat")
                        .HasColumnType("REAL");

                    b.Property<double>("HoursExploration")
                        .HasColumnType("REAL");

                    b.Property<double>("HoursPuzzle")
                        .HasColumnType("REAL");

                    b.Property<int>("NumGames")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Puzzle")
                        .HasColumnType("REAL");

                    b.Property<double?>("SecondMax")
                        .HasColumnType("REAL");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalPlaytime")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("NormalizedProfiles");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManualPreferencesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SteamId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BehaviorWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("CombatProbability")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ExplorationProbability")
                        .HasColumnType("REAL");

                    b.Property<int?>("MissionId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ProfileWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("PuzzleProbability")
                        .HasColumnType("REAL");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecommendedDifficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecommendedType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("SessionId");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.BehaviorEvent", b =>
                {
                    b.HasOne("AdaptiveTrials.Domain.Entities.Mission", "Mission")
                        .WithMany("BehaviorEvents")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdaptiveTrials.Domain.Entities.GameSession", "Session")
                        .WithMany("BehaviorEvents")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.GameSession", b =>
                {
                    b.HasOne("AdaptiveTrials.Domain.Entities.Player", "Player")
                        .WithMany("Sessions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.NormalizedProfile", b =>
                {
                    b.HasOne("AdaptiveTrials.Domain.Entities.Player", "Player")
                        .WithOne("NormalizedProfile")
                        .HasForeignKey("AdaptiveTrials.Domain.Entities.NormalizedProfile", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.Recommendation", b =>
                {
                    b.HasOne("AdaptiveTrials.Domain.Entities.Mission", "Mission")
                        .WithMany("Recommendations")
                        .HasForeignKey("MissionId");

                    b.HasOne("AdaptiveTrials.Domain.Entities.GameSession", "Session")
                        .WithMany("Recommendations")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.GameSession", b =>
                {
                    b.Navigation("BehaviorEvents");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.Mission", b =>
                {
                    b.Navigation("BehaviorEvents");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.Player", b =>
                {
                    b.Navigation("NormalizedProfile");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
