// <auto-generated />
using System;
using AdaptiveTrials.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdaptiveTrials.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702185134_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.BehaviorEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CompletionTime")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Failures")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissionType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Persistence")
                        .HasColumnType("REAL");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("SessionId");

                    b.ToTable("BehaviorEvents");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.NormalizedProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AvgPlaytimePerGame")
                        .HasColumnType("REAL");

                    b.Property<double>("Combat")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Diversity")
                        .HasColumnType("REAL");

                    b.Property<double?>("Dominance")
                        .HasColumnType("REAL");

                    b.Property<double?>("Entropy")
                        .HasColumnType("REAL");

                    b.Property<double>("Exploration")
                        .HasColumnType("REAL");

                    b.Property<int>("GamesCombat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesExploration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesPuzzle")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Gap")
                        .HasColumnType("REAL");

                    b.Property<double>("HoursCombat")
                        .HasColumnType("REAL");

                    b.Property<double>("HoursExploration")
                        .HasColumnType("REAL");

                    b.Property<double>("HoursPuzzle")
                        .HasColumnType("REAL");

                    b.Property<int>("NumGames")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Puzzle")
                        .HasColumnType("REAL");

                    b.Property<double?>("SecondMax")
                        .HasColumnType("REAL");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalPlaytime")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("NormalizedProfiles");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManualPreferencesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SteamId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BehaviorWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("CombatProbability")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ExplorationProbability")
                        .HasColumnType("REAL");

                    b.Property<int?>("MissionId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ProfileWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("PuzzleProbability")
                        .HasColumnType("REAL");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecommendedDifficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecommendedType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("SessionId");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.BehaviorEvent", b =>
                {
                    b.HasOne("AdaptiveTrials.Domain.Entities.Mission", "Mission")
                        .WithMany("BehaviorEvents")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdaptiveTrials.Domain.Entities.GameSession", "Session")
                        .WithMany("BehaviorEvents")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.GameSession", b =>
                {
                    b.HasOne("AdaptiveTrials.Domain.Entities.Player", "Player")
                        .WithMany("Sessions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.NormalizedProfile", b =>
                {
                    b.HasOne("AdaptiveTrials.Domain.Entities.Player", "Player")
                        .WithOne("NormalizedProfile")
                        .HasForeignKey("AdaptiveTrials.Domain.Entities.NormalizedProfile", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.Recommendation", b =>
                {
                    b.HasOne("AdaptiveTrials.Domain.Entities.Mission", "Mission")
                        .WithMany("Recommendations")
                        .HasForeignKey("MissionId");

                    b.HasOne("AdaptiveTrials.Domain.Entities.GameSession", "Session")
                        .WithMany("Recommendations")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.GameSession", b =>
                {
                    b.Navigation("BehaviorEvents");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.Mission", b =>
                {
                    b.Navigation("BehaviorEvents");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("AdaptiveTrials.Domain.Entities.Player", b =>
                {
                    b.Navigation("NormalizedProfile");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
